package uz.pdp.apporderservice.bot.utils;

public interface BotConstant {

    String SHARE_CONTACT = "Kontaktni yuborish";
    String NEW_ORDER = "Yangi buyurtma";
    String EXISTING_ORDER = "MAvjud buyurtma";
    String CHANGE_EXISTING_ORDER_PRICE= "Mavjud buyurtmani narxini o'zgartirish";
    String REFRESH_CABINET_PAGE = "REFRESH_CABINET_PAGE";
    String APLY_ORDER_WITH_NEW_PRICE = "APLY_ORDER_WITH_NEW_PRICE";
    String ACTIVE_ORDER_PAGE= "ACTIVE_ORDER_PAGE";
    String HELP= "HELP";
    String IGNORE_ORDER= "IGNORE_ORDER";
    String ALLOW_IGNORE_ORDER= "ALLOW_IGNORE_ORDER";
    String NOT_ALLOW_IGNORE_ORDER= "NOT_ALLOW_IGNORE_ORDER";
    String CUSTOMER_IGNORE_ORDER_IGNORE= "CUSTOMER_IGNORE_ORDER_IGNORE";
    String CUSTOMER_IGNORE_ALLOW= "CUSTOMER_IGNORE_ALLOW";
    String BALANCE= "BALANCE";
    String SETTINGS= "SETTINGS";
    String ADD_ORDER_AGAIN= "ADD_ORDER_AGAIN";
    String FINISH_ORDER= "CLOSE_ORDER";
    String ORDER_IGNORE_BY_CUSTOMER= "ORDER_IGNORE_BY_CUSTOMER";
    String ORDER_ALLOW_BY_CUSTOMER= "ORDER_ALLOW_BY_CUSTOMER";
    String BASKET_ACTIVATE= "BASKET_ACTIVATE";
    String BASKET_ADMIN_IGNORE= "BASKET_ADMIN_IGNORE";
    String BASKET_ADMIN_FINISH= "BASKET_ADMIN_FINISH";
    String BASKET_PAGE= "BASKET_PAGE";




}
