package uz.pdp.apporderservice.bot.utils;

public interface BotState {
    String REGISTRATION_FIRSTNAME="REGISTRATION_FIRSTNAME";
    String REGISTRATION_LASTNAME="REGISTRATION_LASTNAME";
    String REGISTRATION_PATRON="REGISTRATION_PATRON";
    String REGISTRATION_PASSWORD="REGISTRATION_PASSWORD";
    String CHECK_PASSWORD="CHECK_PASSWORD";
    String CABINET_PAGE="CABINET_PAGE";
    String ADMIN_CABINET="ADMIN_CABINET";
    String ADMIN_CUSTOMER_CHAT="ADMIN_CUSTOMER_CHAT";
    String REPLY_TO_CUSTOMER="REPLY_TO_CUSTOMER";

}
